# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestBuffer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Protobuf'
  pod 'AFNetworking', '~> 3.2.1'
  # Pods for TestBuffer

  target 'TestBufferTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestBufferUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
